config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root to: 'dashboard#index'
    resources :users do
      member do
        patch :disable
      end
    end
    resources :versions, only: [:index, :show]
    resources :companies, only: [:index, :new, :create, :edit, :update]
    resources :projects do
      delete 'attachments/:attachment_id', to: 'projects#delete_attachment', as: :attachment
    end
    resources :todo_lists
    resources :tasks
    resources :comments, only: [:index, :destroy]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # Dashboard dla zalogowanych użytkowników
  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end

  # Publiczna strona główna dla niezalogowanych
  root 'pages#dashboard'

  # Dostęp użytkownika do projektów i zadań
  resources :projects, only: [:index, :show, :edit, :update] do
    resources :todo_lists, only: [:show, :new, :create]
  end

  resources :todo_lists, only: [:show] do
    resources :tasks, only: [:new, :create]
  end

  resources :tasks, only: [:index, :show, :update, :edit] do
    member do
      patch :change_status
    end
    resources :comments, only: [:create, :destroy]
  end
  resources :kanban, only: [:index] do
    collection do
      post :update_status
    end
  end

  resources :notifications, only: [:index] do
    member do
      post :mark_as_read
      post :mark_as_unread
    end

    collection do
      post :mark_all_as_read
    end
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :project
  has_many :tasks, -> { order(position: :asc) }, dependent: :destroy

  validates :name, presence: true

  acts_as_list scope: :project


  def self.ransackable_attributes(auth_object = nil)
    %w[name project_id position created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[project tasks]
  end
end

app/controllers/admin/todo_lists_controller.rb
class Admin::TodoListsController < Admin::ResourcesController
  def index
    set_form_variables
    @q = resource_class.accessible_by(current_ability)
                      .includes(:project)
                      .ransack(params[:q])

    @resources = @q.result
                  .page(params[:page])
                  .per(20)
  end

  private

  def resource_class
    TodoList
  end

  def resource_params
    params.require(:todo_list).permit(:name, :project_id, :position)
  end


  def set_form_variables
    @projects = if current_user.superadmin?
      Project.all
    else
      Project.where(company_id: current_user.company_id)
    end
  end
end

app/controllers/todo_lists_controller.rb
# app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :project, only: [:new, :create]
  load_and_authorize_resource :todo_list, through: :project, shallow: true

  def show
    @tasks = @todo_list.tasks.includes(:assignee).order(position: :asc)
  end

  def new
    @todo_list = @project.todo_lists.build
  end

  def create
    @todo_list = @project.todo_lists.build(todo_list_params)

    if @todo_list.save
      redirect_to project_path(@project), notice: "Lista zadań została utworzona"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:name, :position)
  end
end

app/views/admin/todo_lists/_form.html.slim
= form_with model: [:admin, resource], local: true do |f|
  - if resource.errors.any?
    .alert.alert-danger
      h6 = t('errors.template.header', count: resource.errors.count)
      ul.mb-0
        - resource.errors.full_messages.each do |msg|
          li = msg

  .mb-3
    = f.label :name, class: 'form-label'
    = f.text_field :name, class: 'form-control'
  
  .mb-3
    = f.label :project_id, class: 'form-label'
    = f.collection_select :project_id, 
        @projects,
        :id,
        :name,
        { include_blank: true },
        class: 'form-control'

  .text-end.mt-3
    = link_to t('admin.shared.cancel'), admin_todo_lists_path, class: 'btn btn-link'
    = f.submit t('admin.shared.save'), class: 'btn btn-primary'

app/views/admin/todo_lists/index.html.slim
= content_for :title, t('.title')

.card
  .card-header.d-flex.justify-content-between.align-items-center
    h5.card-title.mb-0 = t('.title')
    = link_to t('.new'), new_admin_todo_list_path, class: 'btn btn-primary'

  .card-body
    = search_form_for [:admin, @q], class: 'mb-4' do |f|
      .row.g-3
        .col-md-4
          = f.label :name_cont, class: 'form-label'
          = f.search_field :name_cont, class: 'form-control'
        
        .col-md-4
          = f.label :project_id_eq, class: 'form-label'
          = f.collection_select :project_id_eq, 
            @projects, 
            :id, 
            :name, 
            { include_blank: true }, 
            class: 'form-select'
            
        .col-12
          = f.submit t('admin.shared.filter'), class: 'btn btn-primary me-2'
          = link_to t('admin.shared.clear_filters'), admin_todo_lists_path, class: 'btn btn-outline-secondary'

    .table-responsive
      table.table
        thead
          tr
            th = sort_link(@q, :name)
            th = TodoList.human_attribute_name(:project)
            th = sort_link(@q, :created_at)
            th
        tbody
          - @resources.each do |todo_list|
            tr
              td = todo_list.name
              td = todo_list.project.name
              td = l(todo_list.created_at, format: :short)
              td.text-end
                = link_to edit_admin_todo_list_path(todo_list), class: 'btn btn-sm btn-outline-primary me-2' do
                  i.bi.bi-pencil
                  =< t('admin.shared.edit')
                = link_to admin_todo_list_path(todo_list), 
                    data: { turbo_method: :delete, turbo_confirm: t('admin.shared.are_you_sure') },
                    class: 'btn btn-sm btn-outline-danger' do
                  i.bi.bi-trash
                  =< t('admin.shared.delete')

    .d-flex.justify-content-center
      = paginate @resources